//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 03:41:10 PM ALMT 
//


package kz.alfabank.cbc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.alfabank.cbc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.alfabank.cbc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HRequest }
     * 
     */
    public HRequest createHRequest() {
        return new HRequest();
    }

    /**
     * Create an instance of {@link HResponse }
     * 
     */
    public HResponse createHResponse() {
        return new HResponse();
    }

    /**
     * Create an instance of {@link ConfirmTransactionMFSRequest }
     * 
     */
    public ConfirmTransactionMFSRequest createConfirmTransactionMFSRequest() {
        return new ConfirmTransactionMFSRequest();
    }

    /**
     * Create an instance of {@link HRequest.Header }
     * 
     */
    public HRequest.Header createHRequestHeader() {
        return new HRequest.Header();
    }

    /**
     * Create an instance of {@link HRequest.Body }
     * 
     */
    public HRequest.Body createHRequestBody() {
        return new HRequest.Body();
    }

    /**
     * Create an instance of {@link TransactionCancelESPPRequest }
     * 
     */
    public TransactionCancelESPPRequest createTransactionCancelESPPRequest() {
        return new TransactionCancelESPPRequest();
    }

    /**
     * Create an instance of {@link StatusTransactionMFSRequest }
     * 
     */
    public StatusTransactionMFSRequest createStatusTransactionMFSRequest() {
        return new StatusTransactionMFSRequest();
    }

    /**
     * Create an instance of {@link ReversMFSCBCRequest }
     * 
     */
    public ReversMFSCBCRequest createReversMFSCBCRequest() {
        return new ReversMFSCBCRequest();
    }

    /**
     * Create an instance of {@link DebitMFSCBCRequest }
     * 
     */
    public DebitMFSCBCRequest createDebitMFSCBCRequest() {
        return new DebitMFSCBCRequest();
    }

    /**
     * Create an instance of {@link MakePaymentESPPRequest }
     * 
     */
    public MakePaymentESPPRequest createMakePaymentESPPRequest() {
        return new MakePaymentESPPRequest();
    }

    /**
     * Create an instance of {@link ReversMFSCBCResponse }
     * 
     */
    public ReversMFSCBCResponse createReversMFSCBCResponse() {
        return new ReversMFSCBCResponse();
    }

    /**
     * Create an instance of {@link HResponse.Header }
     * 
     */
    public HResponse.Header createHResponseHeader() {
        return new HResponse.Header();
    }

    /**
     * Create an instance of {@link HResponse.Body }
     * 
     */
    public HResponse.Body createHResponseBody() {
        return new HResponse.Body();
    }

    /**
     * Create an instance of {@link TransactionApprovalMFSResponse }
     * 
     */
    public TransactionApprovalMFSResponse createTransactionApprovalMFSResponse() {
        return new TransactionApprovalMFSResponse();
    }

    /**
     * Create an instance of {@link TransactionCancelESPPResponse }
     * 
     */
    public TransactionCancelESPPResponse createTransactionCancelESPPResponse() {
        return new TransactionCancelESPPResponse();
    }

    /**
     * Create an instance of {@link PurchaseInitiationMFSResponse }
     * 
     */
    public PurchaseInitiationMFSResponse createPurchaseInitiationMFSResponse() {
        return new PurchaseInitiationMFSResponse();
    }

    /**
     * Create an instance of {@link CreditESPPCBCRequest }
     * 
     */
    public CreditESPPCBCRequest createCreditESPPCBCRequest() {
        return new CreditESPPCBCRequest();
    }

    /**
     * Create an instance of {@link CreditESPPCBCResponse }
     * 
     */
    public CreditESPPCBCResponse createCreditESPPCBCResponse() {
        return new CreditESPPCBCResponse();
    }

    /**
     * Create an instance of {@link CheckPhoneESPPResponse }
     * 
     */
    public CheckPhoneESPPResponse createCheckPhoneESPPResponse() {
        return new CheckPhoneESPPResponse();
    }

    /**
     * Create an instance of {@link ConfirmTransactionMFSResponse }
     * 
     */
    public ConfirmTransactionMFSResponse createConfirmTransactionMFSResponse() {
        return new ConfirmTransactionMFSResponse();
    }

    /**
     * Create an instance of {@link GetBalanceCBCResponse }
     * 
     */
    public GetBalanceCBCResponse createGetBalanceCBCResponse() {
        return new GetBalanceCBCResponse();
    }

    /**
     * Create an instance of {@link MakePaymentESPPResponse }
     * 
     */
    public MakePaymentESPPResponse createMakePaymentESPPResponse() {
        return new MakePaymentESPPResponse();
    }

    /**
     * Create an instance of {@link CheckPhoneESPPRequest }
     * 
     */
    public CheckPhoneESPPRequest createCheckPhoneESPPRequest() {
        return new CheckPhoneESPPRequest();
    }

    /**
     * Create an instance of {@link RefundTransactionMFSResponse }
     * 
     */
    public RefundTransactionMFSResponse createRefundTransactionMFSResponse() {
        return new RefundTransactionMFSResponse();
    }

    /**
     * Create an instance of {@link ChargeConfirmationMFSResponse }
     * 
     */
    public ChargeConfirmationMFSResponse createChargeConfirmationMFSResponse() {
        return new ChargeConfirmationMFSResponse();
    }

    /**
     * Create an instance of {@link CheckCallBDRequest }
     * 
     */
    public CheckCallBDRequest createCheckCallBDRequest() {
        return new CheckCallBDRequest();
    }

    /**
     * Create an instance of {@link TransactionApprovalMFSRequest }
     * 
     */
    public TransactionApprovalMFSRequest createTransactionApprovalMFSRequest() {
        return new TransactionApprovalMFSRequest();
    }

    /**
     * Create an instance of {@link StatusTransactionMFSResponse }
     * 
     */
    public StatusTransactionMFSResponse createStatusTransactionMFSResponse() {
        return new StatusTransactionMFSResponse();
    }

    /**
     * Create an instance of {@link ChargeConfirmationMFSRequest }
     * 
     */
    public ChargeConfirmationMFSRequest createChargeConfirmationMFSRequest() {
        return new ChargeConfirmationMFSRequest();
    }

    /**
     * Create an instance of {@link GetBalanceCBCRequest }
     * 
     */
    public GetBalanceCBCRequest createGetBalanceCBCRequest() {
        return new GetBalanceCBCRequest();
    }

    /**
     * Create an instance of {@link PurchaseInitiationMFSRequest }
     * 
     */
    public PurchaseInitiationMFSRequest createPurchaseInitiationMFSRequest() {
        return new PurchaseInitiationMFSRequest();
    }

    /**
     * Create an instance of {@link RefundTransactionMFSRequest }
     * 
     */
    public RefundTransactionMFSRequest createRefundTransactionMFSRequest() {
        return new RefundTransactionMFSRequest();
    }

    /**
     * Create an instance of {@link DebitMFSCBCResponse }
     * 
     */
    public DebitMFSCBCResponse createDebitMFSCBCResponse() {
        return new DebitMFSCBCResponse();
    }

    /**
     * Create an instance of {@link CheckCallBDResponse }
     * 
     */
    public CheckCallBDResponse createCheckCallBDResponse() {
        return new CheckCallBDResponse();
    }

}
